# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2022.4.26-h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2021.4.0-h06a4308_3561.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.38-h1181459_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ripgrep-12.1.1-0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2021.4.0-h06a4308_640.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/liblief-0.11.5-h295c915_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libsodium-1.0.18-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.3-h295c915_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.3-h7f8727e_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1p-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/patchelf-0.13-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.12-h7f8727e_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20210910-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.14-h74e7548_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.1.2-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.12-h1ccaba5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.3.4-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.2-ha4553b6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.19.2-hac12032_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libarchive-3.5.2-h5de8990_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.38.3-hc218d9a_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpq-12.9-hc2c5182_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.8.10-h12debd9_8.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/catalogue-2.0.7-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2022.6.15-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/chardet-4.0.0-py38h06a4308_1003.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/click-8.0.4-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/colorama-0.4.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cymem-2.0.6-py38h295c915_0.conda
https://repo.anaconda.com/pkgs/main/noarch/dataclasses-0.8-pyh6d0b6a4_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/debugpy-1.5.1-py38h295c915_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/entrypoints-0.4-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/filelock-3.6.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/glob2-0.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/idna-3.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/itsdangerous-2.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.0.1-py38h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/murmurhash-1.0.7-py38h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nest-asyncio-1.5.5-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/noarch/pkginfo-1.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.8.0-py38h27cfd23_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/psycopg2-2.8.6-py38h3c74f83_1.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/py-lief-0.11.5-py38h295c915_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pycosat-0.6.3-py38h7b6447c_1.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.11.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-3.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-libarchive-c-2.9-pyhd3eb1b0_1.conda
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.8-2_cp38.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2022.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-6.0-py38h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-22.3.0-py38h295c915_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/ruamel_yaml-0.15.100-py38h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/noarch/shellingham-1.3.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/smart_open-5.2.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/soupsieve-2.3.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/spacy-legacy-3.0.9-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.1-py38h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tqdm-4.64.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/traitlets-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-4.1.1-pyh06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wasabi-0.9.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.37.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/beautifulsoup4-4.11.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.15.0-py38hd667e15_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/conda-package-handling-1.8.1-py38h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.18.1-py38h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_core-4.10.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/matplotlib-inline-0.1.2-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py38h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/noarch/packaging-21.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/preshed-3.0.6-py38h295c915_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt-toolkit-3.0.20-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-61.2.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/srsly-2.4.3-py38h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typer-0.4.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/typing-extensions-4.1.1-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/werkzeug-2.0.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py38h27cfd23_1003.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-37.0.1-py38h9ce1e76_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jinja2-2.11.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_client-7.2.2-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.22.3-py38hf524024_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pathy-0.6.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-21.2.4-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pydantic-1.8.2-py38h7f8727e_0.conda
https://conda.anaconda.org/conda-forge/noarch/spacy-model-en_core_web_lg-3.1.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/flask-1.1.2-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipython-8.3.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyopenssl-22.0.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-6.9.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.9-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/requests-2.27.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/conda-4.13.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/conda-build-3.21.9-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bottleneck-1.3.4-py38hce1f21e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cython-blis-0.7.7-py38hce1f21e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.1-py38hd3c417c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.2-py38h51133e4_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.22.3-py38he7a7128_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numexpr-2.8.1-py38h807cd23_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/thinc-8.0.15-py38hae6d005_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-1.4.2-py38h295c915_0.conda
https://conda.anaconda.org/conda-forge/linux-64/spacy-3.1.3-py38h2b96118_0.tar.bz2
